# Trabajo Final - Aprendizaje Profundo

## Ejercicio 4

### Alumno: Domenje Carlos

### ✒️ Enunciado

Se tiene la función y = a * log(b) + b * c^2. Calcular las derivadas de y respecto a los
parámetros a, b, c, evaluando en los valores a=2, b=10, c=0.5. Se deben calcular las
derivadas por los siguientes métodos:

- Utilizando derivadas analíticas (symbolic differentiation).

- Utilizando límite con un delta numérico pequeño (numerical differentiation).

- Utilizando grafos y la regla de la cadena (chain rule differentiation)

- Utilizando PyTorch (automatic differentiation).

#### 4.1 Utilización de Derivadas Analíticas

![](img/ej4-1.png)

#### 4.2 Utilización de Límite

![](img/ej4-2_1.png)
![](img/ej4-2_2.png)

#### 4.3 Utilización de Grafos

![](img/ej4-3.png)

#### 4.4 Utilización de PyTorch

In [1]:
import torch 
import math 

In [2]:
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([10.], requires_grad=True)
c = torch.tensor([0.5], requires_grad=True)

y = (a * torch.log(b)) + (b * torch.pow(c, 2))
y.backward()

In [3]:
print(a.grad)
print(b.grad)
print(c.grad)

tensor([2.3026])
tensor([0.4500])
tensor([10.])
